### ISSUE TITLE
Can't compile thinc on Macbook Air M1

### ISSUE THREAD

**Issue by amal1us** [explosion/thinc-apple-ops#11] opened 2022-01-23 10:59 UTC
Hello, I find myself unable to compile this otherwise magnificent tool! Please help, if you can!

I am on MacOS 12.1, Kernel Version 21.2.0, and have installed the latest Python (3.10.2)

Here is the error message I get after trying to install with pip (apparently it can't find the Accelerate Libraries, especially Accelerate.h Header ...): 

 

> ERROR: Command errored out with exit status 1:
>    command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/n7/t2plqm6n2jq4khmj0bckswg40000gq/T/tmp0bhlw2sh
>        cwd: /private/var/folders/n7/t2plqm6n2jq4khmj0bckswg40000gq/T/pip-install-wgga78t9/thinc-apple-ops_f5b38888c7a149cd9f99fd524c2bd340
>   Complete output (34 lines):
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.macosx-10.9-universal2-3.10
>   creating build/lib.macosx-10.9-universal2-3.10/thinc_apple_ops
>   copying thinc_apple_ops/__init__.py -> build/lib.macosx-10.9-universal2-3.10/thinc_apple_ops
>   copying thinc_apple_ops/ops.py -> build/lib.macosx-10.9-universal2-3.10/thinc_apple_ops
>   creating build/lib.macosx-10.9-universal2-3.10/thinc_apple_ops/tests
>   copying thinc_apple_ops/tests/__init__.py -> build/lib.macosx-10.9-universal2-3.10/thinc_apple_ops/tests
>   copying thinc_apple_ops/tests/test_gemm.py -> build/lib.macosx-10.9-universal2-3.10/thinc_apple_ops/tests
>   running egg_info
>   warning: no files found matching '*.pxd' under directory 'thinc_apple_ops'
>   warning: no files found matching '*.txt' under directory 'thinc_apple_ops'
>   writing manifest file 'thinc_apple_ops.egg-info/SOURCES.txt'
>   copying thinc_apple_ops/blas.pyx -> build/lib.macosx-10.9-universal2-3.10/thinc_apple_ops
>   copying thinc_apple_ops/py.typed -> build/lib.macosx-10.9-universal2-3.10/thinc_apple_ops
>   running build_ext
>   creating build/temp.macosx-10.9-universal2-3.10
>   creating build/temp.macosx-10.9-universal2-3.10/thinc_apple_ops
>   clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/n7/t2plqm6n2jq4khmj0bckswg40000gq/T/pip-build-env-b0flamc2/overlay/lib/python3.10/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c thinc_apple_ops/blas.c -o build/temp.macosx-10.9-universal2-3.10/thinc_apple_ops/blas.o
>   In file included from thinc_apple_ops/blas.c:706:
>   In file included from /private/var/folders/n7/t2plqm6n2jq4khmj0bckswg40000gq/T/pip-build-env-b0flamc2/overlay/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5:
>   In file included from /private/var/folders/n7/t2plqm6n2jq4khmj0bckswg40000gq/T/pip-build-env-b0flamc2/overlay/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
>   In file included from /private/var/folders/n7/t2plqm6n2jq4khmj0bckswg40000gq/T/pip-build-env-b0flamc2/overlay/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1960:
>   /private/var/folders/n7/t2plqm6n2jq4khmj0bckswg40000gq/T/pip-build-env-b0flamc2/overlay/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
>   #warning "Using deprecated NumPy API, disable it with " \
>    ^
>   thinc_apple_ops/blas.c:714:10: fatal error: 'Accelerate/Accelerate.h' file not found
>   #include "Accelerate/Accelerate.h"
>            ^~~~~~~~~~~~~~~~~~~~~~~~~
>   thinc_apple_ops/blas.c:714:10: note: did not find header 'Accelerate.h' in framework 'Accelerate' (loaded from '/System/Library/Frameworks')
>   1 warning and 1 error generated.
>   error: command '/Library/Developer/CommandLineTools/usr/bin/clang' failed with exit code 1
>   ----------------------------------------
>   ERROR: Failed building wheel for thinc-apple-ops
> Failed to build thinc-apple-ops
> ERROR: Could not build wheels for thinc-apple-ops, which is required to install pyproject.toml-based projects
> 

------------------------------------------ END---------------------------------------------------------------------------

Any help would be greatly appreciated, thanks!

**Comment by polm** [comment] 2022-01-23 11:47
Duplicate of https://github.com/explosion/spaCy/discussions/10116. Please don't multi-post, if you don't know the right place to post just pick one place.

**Closed by polm** 2022-01-23 11:47 UTC
